/**
 * Jotform to Lofty webhook - Cloudflare Worker
 * ----------------------------------------------
 * Receives post-showing feedback submissions from Jotform and:
 *   1. Writes a note to the matching Lofty lead.
 *   2. Emails the buyer a recap.
 *   3. Writes one row to the D1 showing_feedback table.
 *
 * Email path (step 2) picks itself based on what's configured:
 *   - If RESEND_API_KEY is set, the recap email goes through Resend
 *     and is delivered to the buyer_email submitted on the form.
 *     Requires a Resend account and a verified sending domain that
 *     matches OWNER_EMAIL.
 *   - Otherwise the recap email goes through Lofty's send_email
 *     endpoint and is delivered to the lead's primary email on file
 *     in Lofty. Zero extra setup, works on day 1.
 *
 * Steps 2 and 3 are non-blocking: if email or D1 fails, the Lofty
 * note still lands and the webhook returns 200 so Jotform doesn't
 * retry and create duplicates.
 *
 * On the 3rd+ submission for a given lead, the recap email gets a
 * "What we're learning about your preferences" section built from
 * the D1 history. Under 3 submissions, the email looks like before.
 *
 * ROUTES:
 *   GET  /                         health check (no auth)
 *   GET  /preferences/:leadId      buyer preferences JSON (Bearer auth)
 *   POST /                         Jotform webhook (no auth, Jotform posts raw)
 *
 * DEPLOY: `wrangler deploy -c workers/wrangler.jotform.toml` (see the
 * comments in that file for one-time D1 + secret setup).
 *
 * SECRETS (set with `wrangler secret put ... -c wrangler.jotform.toml`):
 *   LOFTY_API_KEY         - Lofty personal access token (also used for
 *                           the recap email when RESEND_API_KEY is unset)
 *   RESEND_API_KEY        - Resend API key (optional; if absent, recap
 *                           email falls back to Lofty's send_email)
 *   PREFERENCES_API_KEY   - Bearer token gating GET /preferences/:leadId
 *
 * VARS (set in wrangler.jotform.toml [vars] block; not secret):
 *   OWNER_FULL_NAME       - your name as it appears on the recap email
 *   OWNER_EMAIL           - your verified Resend "from" address and reply-to
 *   OWNER_PHONE           - shown in the email signature
 *   OWNER_BROKERAGE       - shown in the email signature
 *   OWNER_WEBSITE         - optional website link in the HTML signature
 *   JOTFORM_FIELD_MAP     - JSON string mapping Jotform qid -> purpose tag.
 *                           Populated by the Easy Mode setup after the form
 *                           is built via Jotform MCP. When present, the
 *                           Worker routes submissions by qid instead of
 *                           guessing aliases. Falls back to alias matching
 *                           if blank or invalid JSON.
 *
 * BINDINGS (declared in wrangler.jotform.toml):
 *   DB                    - D1 database showing_feedback
 */

const LOFTY_API_BASE = "https://api.lofty.com/v1.0";

// Minimum submissions a buyer needs before we show them a
// "what we're learning" section in the recap email. Two data points
// is not enough signal; three starts to feel earned.
const MIN_SHOWINGS_FOR_PREFERENCES = 3;

// How many tags to surface in the email enrichment section.
const TOP_LOVED_COUNT = 3;
const TOP_DEALBREAKER_COUNT = 2;

// Rating questions: Jotform field name -> human-readable label + the
// D1 column we persist into. Field names are auto-generated by
// Jotform from the question titles. If you rename a question, add a
// fallback alias here rather than editing the canonical snake_case.
const RATING_FIELDS = [
  { aliases: ["first_reaction", "firstReaction"],    label: "First reaction walking in",     column: "first_reaction" },
  { aliases: ["daily_life_fit", "howDid"],           label: "Daily life fit",                 column: "daily_life_fit" },
  { aliases: ["neighborhood_rating", "whatAbout"],   label: "Neighborhood and location",      column: "neighborhood_rating" },
  { aliases: ["condition_rating", "conditionAnd"],   label: "Condition and move-in readiness", column: "condition_rating" },
  { aliases: ["value_rating", "atThe"],              label: "Value at asking price",          column: "value_rating" },
  { aliases: ["short_list", "doesThis"],             label: "Does this make the short list",  column: "short_list" },
];

// Open-ended text questions.
const TEXT_FIELDS = [
  { aliases: ["standout_text", "whatStood"], label: "What stood out",           column: "standout_text" },
  { aliases: ["memory_notes", "areThere"],   label: "Other things to remember", column: "memory_notes" },
];

// Multi-select tag questions. Phase 2 additions.
// Jotform multi-selects export as either an array or a CSV string
// depending on form settings, so parseTagList handles both.
const TAG_FIELDS = [
  { aliases: ["loved_tags", "whatYouLoved", "whatYou", "loved"],
    label: "What you loved",
    column: "loved_tags" },
  { aliases: ["dealbreaker_tags", "dealbreakers", "dealBreakers"],
    label: "Dealbreakers",
    column: "dealbreaker_tags" },
];

// Pull owner identity from env vars set in wrangler.jotform.toml.
// These flow into the recap email's from/bcc/reply_to/signature.
function ownerFromEnv(env) {
  return {
    fullName: (env.OWNER_FULL_NAME || "").trim(),
    email: (env.OWNER_EMAIL || "").trim(),
    phone: (env.OWNER_PHONE || "").trim(),
    brokerage: (env.OWNER_BROKERAGE || "").trim(),
    website: (env.OWNER_WEBSITE || "").trim(),
  };
}

// Module-scope cache for the qid -> purpose-tag map. Parsed once on
// first read because env values don't change between invocations.
// Expected shape: {"3":"first_reaction","4":"daily_life_fit",...}.
// Empty object = no map configured, fall back to alias matching.
let _fieldIdMapCache = null;
function getFieldIdMap(env) {
  if (_fieldIdMapCache !== null) return _fieldIdMapCache;
  if (!env.JOTFORM_FIELD_MAP) {
    _fieldIdMapCache = {};
    return _fieldIdMapCache;
  }
  try {
    const parsed = JSON.parse(env.JOTFORM_FIELD_MAP);
    _fieldIdMapCache = parsed && typeof parsed === "object" ? parsed : {};
  } catch (e) {
    console.error("Failed to parse JOTFORM_FIELD_MAP env var:", e);
    _fieldIdMapCache = {};
  }
  return _fieldIdMapCache;
}

// Build a reverse index purpose -> qid so we can look up "what qid
// holds the value for the first_reaction question?" in O(1).
function reverseFieldIdMap(fieldIdMap) {
  const reverse = {};
  Object.keys(fieldIdMap).forEach((qid) => {
    const purpose = fieldIdMap[qid];
    if (purpose) reverse[purpose] = String(qid);
  });
  return reverse;
}

// Look up a field config in TEXT_FIELDS / TAG_FIELDS / RATING_FIELDS
// by D1 column name. Used by the email builders so they don't have
// to maintain their own duplicate alias lists.
function fieldByColumn(fieldArray, column) {
  return fieldArray.find((f) => f.column === column);
}

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);

    // Health check
    if (request.method === "GET" && url.pathname === "/") {
      return jsonResponse({ status: "ok", service: "jotform-to-lofty" });
    }

    // Preferences aggregation endpoint
    if (request.method === "GET" && url.pathname.startsWith("/preferences/")) {
      return handlePreferencesRequest(request, env, url);
    }

    if (request.method !== "POST") {
      return jsonResponse({ status: "error", message: "Method not allowed" }, 405);
    }

    try {
      const submission = await parseJotformPost(request);

      const leadId = submission.lead_id;
      // Jotform's create_form agent often normalizes the unique names of
      // hidden fields to lowercase (e.g. propertyAddress -> propertyaddress)
      // even when the prompt asked for a specific case. Read both variants
      // plus the legacy snake_case names from the older form layout.
      const propertyAddress =
        submission.propertyaddress ||
        submission.propertyAddress ||
        submission.property_address_hidden ||
        submission.property_address ||
        "(unknown property)";
      const showingDate =
        submission.showingdate ||
        submission.showingDate ||
        submission.showing_date_hidden ||
        submission.showing_date ||
        formattedToday();

      if (!leadId || leadId === "test") {
        // test submission - log it but don't write to Lofty
        console.log("Test submission, skipping Lofty write:", JSON.stringify(submission));
        return jsonResponse({ status: "ok", skipped: "test lead" });
      }

      if (!env.LOFTY_API_KEY) {
        throw new Error("LOFTY_API_KEY secret is not set in Worker settings.");
      }

      // Build the qid lookup once per request. When unset, the parsers
      // skip qid resolution and fall through to alias matching.
      const fieldIdMap = getFieldIdMap(env);
      const purposeToQid = reverseFieldIdMap(fieldIdMap);

      const noteBody =
        "=== POST-SHOWING FEEDBACK ===\n" +
        propertyAddress + " | " + showingDate + "\n\n" +
        buildNoteBody(submission, propertyAddress, showingDate, purposeToQid);

      const loftyResponse = await createLoftyNote(
        env.LOFTY_API_KEY,
        leadId,
        noteBody
      );

      // Write a row to D1. Non-blocking: any failure is logged but
      // does not fail the webhook (Lofty note already succeeded).
      let d1Result = { skipped: "no DB binding" };
      if (env.DB) {
        try {
          d1Result = await writeFeedbackRow(env.DB, submission, propertyAddress, showingDate, purposeToQid);
        } catch (e) {
          console.error("D1 write failed:", e);
          d1Result = { error: String(e) };
        }
      }

      // Compute preferences for email enrichment. Only query if we
      // have a DB binding and the row we just wrote is not the first
      // one for this lead. Failures here never block the email.
      let preferences = null;
      if (env.DB && Number(leadId)) {
        try {
          preferences = await aggregatePreferences(env.DB, Number(leadId));
        } catch (e) {
          console.error("Preferences aggregation failed:", e);
          preferences = null;
        }
      }

      // Send the buyer a recap email. Path picks itself: Resend if
      // configured, Lofty otherwise. An email failure must NOT block
      // or reverse the Lofty note write.
      let emailResult = { skipped: "no email path available" };
      const buyerEmail = (submission.buyer_email || "").trim();
      const owner = ownerFromEnv(env);
      const recapSubject = "Your feedback for " +
        (propertyAddress.split(",")[0] || propertyAddress) + " is in";
      const recapHtml = buildBuyerEmailHtml(
        submission, propertyAddress, showingDate,
        firstNameFromSubmission(submission), preferences, owner, purposeToQid
      );

      if (env.RESEND_API_KEY) {
        // Resend path: explicit address from the form submission.
        if (buyerEmail) {
          try {
            emailResult = await sendBuyerRecapViaResend(
              env.RESEND_API_KEY,
              buyerEmail,
              recapSubject,
              recapHtml,
              buildBuyerEmailText(
                submission, propertyAddress, showingDate,
                firstNameFromSubmission(submission), preferences, owner, purposeToQid
              ),
              owner
            );
            emailResult.via = "resend";
          } catch (e) {
            console.error("Resend email send failed:", e);
            emailResult = { error: String(e), via: "resend" };
          }
        } else {
          emailResult = { skipped: "no buyer_email submitted", via: "resend" };
        }
      } else {
        // Lofty fallback path: sends to the lead's primary email
        // address on file in Lofty. No extra account setup needed.
        try {
          emailResult = await sendBuyerRecapViaLofty(
            env.LOFTY_API_KEY,
            Number(leadId),
            recapSubject,
            recapHtml
          );
          emailResult.via = "lofty";
        } catch (e) {
          console.error("Lofty email send failed:", e);
          emailResult = { error: String(e), via: "lofty" };
        }
      }

      return jsonResponse({
        status: "ok",
        lofty: loftyResponse,
        email: emailResult,
        d1: d1Result,
        preferences_applied: preferences && preferences.total_showings >= MIN_SHOWINGS_FOR_PREFERENCES,
      });
    } catch (err) {
      console.error("Webhook error:", err);
      return jsonResponse({ status: "error", message: String(err) }, 500);
    }
  },
};

// ---------- /preferences handler ----------

async function handlePreferencesRequest(request, env, url) {
  if (!env.DB) {
    return jsonResponse({ status: "error", message: "DB binding not configured" }, 500);
  }

  const expected = env.PREFERENCES_API_KEY;
  if (!expected) {
    return jsonResponse({ status: "error", message: "PREFERENCES_API_KEY secret is not set" }, 500);
  }

  const authHeader = request.headers.get("authorization") || "";
  const provided = authHeader.replace(/^Bearer\s+/i, "").trim();
  if (provided !== expected) {
    return jsonResponse({ status: "error", message: "Unauthorized" }, 401);
  }

  const leadIdStr = url.pathname.split("/").pop();
  const leadId = Number(leadIdStr);
  if (!leadId || !Number.isFinite(leadId)) {
    return jsonResponse({ status: "error", message: "Invalid lead id" }, 400);
  }

  try {
    const prefs = await aggregatePreferences(env.DB, leadId);
    return jsonResponse({ status: "ok", ...prefs });
  } catch (e) {
    console.error("Preferences query failed:", e);
    return jsonResponse({ status: "error", message: String(e) }, 500);
  }
}

// ---------- parsing helpers ----------

async function parseJotformPost(request) {
  const contentType = request.headers.get("content-type") || "";
  let rawRequest = "";

  if (contentType.includes("application/x-www-form-urlencoded")) {
    const formData = await request.formData();
    rawRequest = formData.get("rawRequest") || "";
  } else if (contentType.includes("multipart/form-data")) {
    const formData = await request.formData();
    rawRequest = formData.get("rawRequest") || "";
  } else if (contentType.includes("application/json")) {
    const body = await request.json();
    rawRequest = body.rawRequest || JSON.stringify(body);
  } else {
    // best effort - try form data first
    try {
      const formData = await request.formData();
      rawRequest = formData.get("rawRequest") || "";
    } catch (e) {
      rawRequest = await request.text();
    }
  }

  const parsed = typeof rawRequest === "string" ? JSON.parse(rawRequest || "{}") : rawRequest;

  const out = {};
  // _byQid is a side-channel index keyed by Jotform's numeric field ID
  // (the "q123" prefix). When a JOTFORM_FIELD_MAP is configured, the
  // Worker uses this for routing instead of trying alias names.
  out._byQid = {};
  Object.keys(parsed).forEach((key) => {
    // Match the "q123_uniqueName" shape Jotform uses. Capture the qid
    // and the cleanKey separately so we can store both.
    const m = key.match(/^q(\d+)_(.*)$/);
    const qid = m ? m[1] : null;
    const cleanKey = m ? m[2] : key;
    const rawValue = parsed[key];
    let value;
    if (Array.isArray(rawValue)) {
      // multi-select: keep as array so parseTagList sees it natively
      value = rawValue.map((v) => String(v).trim()).filter(Boolean);
    } else if (typeof rawValue === "object" && rawValue !== null) {
      // compound fields (name, address, etc.) -> join non-empty parts
      value = Object.values(rawValue).filter(Boolean).join(" ").trim();
    } else {
      value = String(rawValue || "").trim();
    }
    out[cleanKey] = value;
    if (qid) out._byQid[qid] = value;
  });
  return out;
}

// Look up a value by purpose tag, preferring the qid map when set.
// Falls back to undefined; callers handle the fallback to aliases.
function valueByPurpose(submission, purposeToQid, purpose) {
  const qid = purposeToQid[purpose];
  if (!qid) return undefined;
  if (!submission._byQid) return undefined;
  return submission._byQid[qid];
}

// Read a multi-select field from the submission. Returns an array of
// non-empty, trimmed strings. Handles three possible shapes:
//   1. Array already:     ["yard","natural light"]
//   2. CSV string:        "yard, natural light"
//   3. Pipe-delimited:    "yard|natural light"  (Jotform export option)
//
// When purposeToQid is supplied and the qid lookup returns a value,
// that wins. Otherwise the function walks the aliases list.
function parseTagList(submission, aliases, purpose, purposeToQid) {
  const candidates = [];
  if (purpose && purposeToQid && purposeToQid[purpose]) {
    const v = valueByPurpose(submission, purposeToQid, purpose);
    if (v !== undefined) candidates.push(v);
  }
  aliases.forEach((alias) => {
    const v = submission[alias];
    if (v !== undefined) candidates.push(v);
  });
  for (const val of candidates) {
    if (val === null || val === "") continue;
    if (Array.isArray(val)) {
      return val.map((v) => String(v).trim()).filter(Boolean);
    }
    const str = String(val);
    if (!str.trim()) continue;
    // Try pipe first (Jotform's default for multi-select text export),
    // fall back to comma.
    const parts = str.includes("|") ? str.split("|") : str.split(",");
    return parts.map((v) => v.trim()).filter(Boolean);
  }
  return [];
}

// Read a rating value from the submission. Returns an integer 1-5
// or null if missing / unparseable. Same qid-first-then-aliases
// preference as parseTagList.
function parseRating(submission, aliases, purpose, purposeToQid) {
  const candidates = [];
  if (purpose && purposeToQid && purposeToQid[purpose]) {
    const v = valueByPurpose(submission, purposeToQid, purpose);
    if (v !== undefined) candidates.push(v);
  }
  aliases.forEach((alias) => {
    const v = submission[alias];
    if (v !== undefined) candidates.push(v);
  });
  for (const v of candidates) {
    if (v === null || v === "") continue;
    const n = parseInt(String(v), 10);
    if (!isNaN(n) && n >= 1 && n <= 5) return n;
  }
  return null;
}

// Read a text value from the submission. Same qid-first-then-aliases
// preference as parseTagList.
function parseText(submission, aliases, purpose, purposeToQid) {
  const candidates = [];
  if (purpose && purposeToQid && purposeToQid[purpose]) {
    const v = valueByPurpose(submission, purposeToQid, purpose);
    if (v !== undefined) candidates.push(v);
  }
  aliases.forEach((alias) => {
    const v = submission[alias];
    if (v !== undefined) candidates.push(v);
  });
  for (const v of candidates) {
    if (v === null) continue;
    const str = typeof v === "string" ? v : String(v);
    if (str.trim()) return str.trim();
  }
  return "";
}

// ---------- note body builder (goes to Lofty) ----------

function buildNoteBody(submission, propertyAddress, showingDate, purposeToQid) {
  const lines = [];
  lines.push("Property: " + propertyAddress);
  lines.push("Showing date: " + showingDate);
  const propertyStats = submission.propertystats || submission.propertyStats || submission.property_stats;
  if (propertyStats) lines.push("Stats: " + propertyStats);
  if (submission.client_name) lines.push("Client: " + submission.client_name);
  lines.push("");

  // Ratings block
  const ratingLines = [];
  RATING_FIELDS.forEach((f) => {
    const n = parseRating(submission, f.aliases, f.column, purposeToQid);
    if (n !== null) ratingLines.push(formatRating(f.label, n));
  });

  if (ratingLines.length > 0) {
    lines.push("RATINGS");
    lines.push("-------");
    ratingLines.forEach((l) => lines.push(l));
    lines.push("");
  }

  // Tag blocks (loved / dealbreakers)
  TAG_FIELDS.forEach((f) => {
    const tags = parseTagList(submission, f.aliases, f.column, purposeToQid);
    if (tags.length > 0) {
      lines.push(f.label.toUpperCase());
      lines.push("-".repeat(f.label.length));
      tags.forEach((t) => lines.push("- " + t));
      lines.push("");
    }
  });

  // Text responses
  const textLines = [];
  TEXT_FIELDS.forEach((f) => {
    const v = parseText(submission, f.aliases, f.column, purposeToQid);
    if (v) {
      textLines.push(f.label + ":");
      textLines.push(v);
      textLines.push("");
    }
  });

  if (textLines.length > 0) {
    lines.push("FEEDBACK");
    lines.push("--------");
    textLines.forEach((l) => lines.push(l));
  }

  lines.push("(Submitted via post-showing feedback form)");
  return lines.join("\n");
}

function formatRating(label, value) {
  const n = parseInt(value, 10);
  if (!isNaN(n) && n >= 1 && n <= 5) {
    const stars = "*".repeat(n) + "-".repeat(5 - n);
    return label + ": " + stars + " (" + n + "/5)";
  }
  return label + ": " + value;
}

async function createLoftyNote(apiKey, leadId, body) {
  const url = LOFTY_API_BASE + "/notes";
  const response = await fetch(url, {
    method: "POST",
    headers: {
      Authorization: "token " + apiKey,
      Accept: "application/json",
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ leadId: Number(leadId), content: body }),
  });

  const text = await response.text();
  if (!response.ok) {
    throw new Error("Lofty API " + response.status + ": " + text);
  }
  try {
    return JSON.parse(text);
  } catch (e) {
    return { raw: text };
  }
}

// ---------- D1 write ----------

async function writeFeedbackRow(db, submission, propertyAddress, showingDate, purposeToQid) {
  const leadId = Number(submission.lead_id);
  if (!leadId || !Number.isFinite(leadId)) {
    return { skipped: "invalid lead_id" };
  }

  const submittedAt = new Date().toISOString();

  const ratings = {};
  RATING_FIELDS.forEach((f) => {
    ratings[f.column] = parseRating(submission, f.aliases, f.column, purposeToQid);
  });

  const texts = {};
  TEXT_FIELDS.forEach((f) => {
    texts[f.column] = parseText(submission, f.aliases, f.column, purposeToQid) || null;
  });

  const tags = {};
  TAG_FIELDS.forEach((f) => {
    const parsed = parseTagList(submission, f.aliases, f.column, purposeToQid);
    tags[f.column] = parsed.length > 0 ? JSON.stringify(parsed) : null;
  });

  const stmt = db.prepare(
    "INSERT INTO showing_feedback (" +
      "submitted_at, lead_id, property_address, showing_date, " +
      "first_reaction, daily_life_fit, neighborhood_rating, " +
      "condition_rating, value_rating, short_list, " +
      "standout_text, memory_notes, " +
      "loved_tags, dealbreaker_tags, claude_tags, " +
      "raw_submission" +
    ") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
  );

  const result = await stmt
    .bind(
      submittedAt,
      leadId,
      propertyAddress,
      showingDate || null,
      ratings.first_reaction,
      ratings.daily_life_fit,
      ratings.neighborhood_rating,
      ratings.condition_rating,
      ratings.value_rating,
      ratings.short_list,
      texts.standout_text,
      texts.memory_notes,
      tags.loved_tags,
      tags.dealbreaker_tags,
      null, // claude_tags reserved for future
      JSON.stringify(submission)
    )
    .run();

  return {
    inserted: true,
    row_id: result.meta && result.meta.last_row_id,
    lead_id: leadId,
  };
}

// ---------- preferences aggregation ----------

async function aggregatePreferences(db, leadId) {
  const { results } = await db
    .prepare(
      "SELECT first_reaction, daily_life_fit, neighborhood_rating, " +
        "condition_rating, value_rating, short_list, " +
        "loved_tags, dealbreaker_tags " +
      "FROM showing_feedback WHERE lead_id = ? ORDER BY submitted_at ASC"
    )
    .bind(leadId)
    .all();

  const total = results ? results.length : 0;

  const lovedCounts = {};
  const dealbreakerCounts = {};
  const ratingTotals = {
    first_reaction: { sum: 0, n: 0 },
    daily_life_fit: { sum: 0, n: 0 },
    neighborhood_rating: { sum: 0, n: 0 },
    condition_rating: { sum: 0, n: 0 },
    value_rating: { sum: 0, n: 0 },
    short_list: { sum: 0, n: 0 },
  };

  (results || []).forEach((row) => {
    tally(row.loved_tags, lovedCounts);
    tally(row.dealbreaker_tags, dealbreakerCounts);
    Object.keys(ratingTotals).forEach((k) => {
      const v = row[k];
      if (typeof v === "number") {
        ratingTotals[k].sum += v;
        ratingTotals[k].n += 1;
      }
    });
  });

  const averageRatings = {};
  Object.keys(ratingTotals).forEach((k) => {
    const t = ratingTotals[k];
    averageRatings[k] = t.n > 0 ? Number((t.sum / t.n).toFixed(2)) : null;
  });

  return {
    lead_id: leadId,
    total_showings: total,
    loved: sortCounts(lovedCounts),
    dealbreakers: sortCounts(dealbreakerCounts),
    average_ratings: averageRatings,
  };
}

function tally(jsonArrayString, counts) {
  if (!jsonArrayString) return;
  let arr;
  try {
    arr = JSON.parse(jsonArrayString);
  } catch (e) {
    return;
  }
  if (!Array.isArray(arr)) return;
  arr.forEach((tag) => {
    const key = String(tag).trim();
    if (!key) return;
    counts[key] = (counts[key] || 0) + 1;
  });
}

function sortCounts(counts) {
  return Object.keys(counts)
    .map((tag) => ({ tag, count: counts[tag] }))
    .sort((a, b) => b.count - a.count || a.tag.localeCompare(b.tag));
}

// ---------- email helpers ----------

function formattedToday() {
  const now = new Date();
  const month = now.toLocaleString("en-US", { month: "long", timeZone: "America/Los_Angeles" });
  const day = now.toLocaleString("en-US", { day: "numeric", timeZone: "America/Los_Angeles" });
  const year = now.toLocaleString("en-US", { year: "numeric", timeZone: "America/Los_Angeles" });
  return month + " " + day + ", " + year;
}

function jsonResponse(obj, status = 200) {
  return new Response(JSON.stringify(obj), {
    status,
    headers: { "Content-Type": "application/json" },
  });
}

// Pull the buyer's first name from the form submission. Used in the
// recap email greeting. Falls back to "there" when the form did not
// capture a client name.
function firstNameFromSubmission(submission) {
  const clientName = (submission.client_name || "").trim();
  return clientName.split(" ")[0] || "there";
}

// Send the buyer recap via Resend. Used when RESEND_API_KEY is set.
// Caller is responsible for building the subject + bodies; this
// function just wraps the HTTP call.
async function sendBuyerRecapViaResend(resendApiKey, toEmail, subject, htmlBody, textBody, owner) {
  if (!owner.fullName || !owner.email) {
    throw new Error("OWNER_FULL_NAME and OWNER_EMAIL must be set in wrangler.jotform.toml [vars] for the Resend path.");
  }
  const fromAddress = owner.fullName + " <" + owner.email + ">";

  const response = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      Authorization: "Bearer " + resendApiKey,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      from: fromAddress,
      to: [toEmail],
      bcc: [owner.email],
      reply_to: owner.email,
      subject: subject,
      html: htmlBody,
      text: textBody,
    }),
  });

  const text = await response.text();
  if (!response.ok) {
    throw new Error("Resend API " + response.status + ": " + text);
  }
  try {
    return JSON.parse(text);
  } catch (e) {
    return { raw: text };
  }
}

// Send the buyer recap via Lofty's send_email endpoint. Used as the
// fallback when RESEND_API_KEY is unset. Lofty sends to whatever
// email address is on the lead record, so we don't need a separate
// "to" address. Lofty also sends from the agent's connected mailbox,
// so no domain verification is required.
async function sendBuyerRecapViaLofty(loftyApiKey, leadId, subject, htmlBody) {
  if (!loftyApiKey) {
    throw new Error("LOFTY_API_KEY secret is required for the Lofty email fallback.");
  }
  if (!leadId || !Number.isFinite(leadId)) {
    throw new Error("Lofty email send requires a valid numeric leadId.");
  }
  const response = await fetch(LOFTY_API_BASE + "/message/email/send", {
    method: "POST",
    headers: {
      Authorization: "token " + loftyApiKey,
      Accept: "application/json",
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      leadId: leadId,
      subject: subject,
      content: htmlBody,
    }),
  });

  const text = await response.text();
  if (!response.ok) {
    throw new Error("Lofty API " + response.status + ": " + text);
  }
  try {
    return JSON.parse(text);
  } catch (e) {
    return { raw: text };
  }
}

// Pick the top N loved + top M dealbreakers for the enrichment
// section. Returns null when the buyer doesn't have enough history
// yet or when there's no signal to share.
function selectPreferencesForEmail(preferences) {
  if (!preferences) return null;
  if ((preferences.total_showings || 0) < MIN_SHOWINGS_FOR_PREFERENCES) return null;
  const loved = (preferences.loved || []).slice(0, TOP_LOVED_COUNT);
  const dealbreakers = (preferences.dealbreakers || []).slice(0, TOP_DEALBREAKER_COUNT);
  if (loved.length === 0 && dealbreakers.length === 0) return null;
  return { total_showings: preferences.total_showings, loved, dealbreakers };
}

function buildBuyerEmailText(submission, propertyAddress, showingDate, firstName, preferences, owner, purposeToQid) {
  const stats = submission.propertyStats || "";

  const ratingRows = [];
  RATING_FIELDS.forEach((f) => {
    const n = parseRating(submission, f.aliases, f.column, purposeToQid);
    if (n !== null) {
      const label = f.label === "Does this make the short list" ? "Does this make your short list" : f.label;
      ratingRows.push(label + ": " + n + " of 5 stars");
    }
  });

  const standoutF = fieldByColumn(TEXT_FIELDS, "standout_text");
  const memoryF = fieldByColumn(TEXT_FIELDS, "memory_notes");
  const lovedF = fieldByColumn(TAG_FIELDS, "loved_tags");
  const dealF = fieldByColumn(TAG_FIELDS, "dealbreaker_tags");
  const standout = parseText(submission, standoutF.aliases, standoutF.column, purposeToQid);
  const memory = parseText(submission, memoryF.aliases, memoryF.column, purposeToQid);
  const lovedThisTime = parseTagList(submission, lovedF.aliases, lovedF.column, purposeToQid);
  const dealbreakersThisTime = parseTagList(submission, dealF.aliases, dealF.column, purposeToQid);

  const prefs = selectPreferencesForEmail(preferences);

  const lines = [];
  lines.push("Hi " + firstName + ",");
  lines.push("");
  lines.push("Thanks for sending your feedback on the home we toured on " + showingDate + ".");
  lines.push("Here is a recap for your records.");
  lines.push("");
  lines.push("Property");
  lines.push(propertyAddress);
  if (stats) lines.push(stats);
  lines.push("");
  if (ratingRows.length > 0) {
    lines.push("Your Ratings");
    ratingRows.forEach((r) => lines.push(r));
    lines.push("");
  }
  if (lovedThisTime.length > 0) {
    lines.push("What you loved about this one");
    lovedThisTime.forEach((t) => lines.push("- " + t));
    lines.push("");
  }
  if (dealbreakersThisTime.length > 0) {
    lines.push("Dealbreakers on this one");
    dealbreakersThisTime.forEach((t) => lines.push("- " + t));
    lines.push("");
  }
  if (standout) {
    lines.push("What stood out");
    lines.push(standout);
    lines.push("");
  }
  if (memory) {
    lines.push("Other things to remember");
    lines.push(memory);
    lines.push("");
  }
  if (prefs) {
    lines.push("What we're learning about your preferences");
    lines.push("(based on your feedback across " + prefs.total_showings + " showings)");
    if (prefs.loved.length > 0) {
      lines.push("");
      lines.push("Things you keep coming back to:");
      prefs.loved.forEach((item) => lines.push("- " + item.tag + " (" + item.count + " of " + prefs.total_showings + ")"));
    }
    if (prefs.dealbreakers.length > 0) {
      lines.push("");
      lines.push("Things to avoid:");
      prefs.dealbreakers.forEach((item) => lines.push("- " + item.tag + " (" + item.count + " of " + prefs.total_showings + ")"));
    }
    lines.push("");
  }
  lines.push("If anything changed or you want to add to this, just reply to this email.");
  lines.push("");
  lines.push(owner.fullName);
  if (owner.brokerage) lines.push(owner.brokerage);
  if (owner.phone) lines.push(owner.phone);
  if (owner.email) lines.push(owner.email);
  return lines.join("\n");
}

function buildBuyerEmailHtml(submission, propertyAddress, showingDate, firstName, preferences, owner, purposeToQid) {
  const stats = submission.propertyStats || "";

  const ratingRowsHtml = [];
  RATING_FIELDS.forEach((f) => {
    const n = parseRating(submission, f.aliases, f.column, purposeToQid);
    if (n !== null) {
      const label = f.label === "Does this make the short list" ? "Does this make your short list" : f.label;
      const stars = "&#9733;".repeat(n) + "&#9734;".repeat(5 - n);
      ratingRowsHtml.push(
        "<tr>" +
          '<td style="padding:4px 12px 4px 0;color:#444;">' + escapeHtml(label) + "</td>" +
          '<td style="padding:4px 0;color:#C89F50;font-size:16px;letter-spacing:2px;">' + stars +
          ' <span style="color:#888;font-size:13px;letter-spacing:0;">(' + n + "/5)</span></td>" +
        "</tr>"
      );
    }
  });

  const standoutF = fieldByColumn(TEXT_FIELDS, "standout_text");
  const memoryF = fieldByColumn(TEXT_FIELDS, "memory_notes");
  const lovedF = fieldByColumn(TAG_FIELDS, "loved_tags");
  const dealF = fieldByColumn(TAG_FIELDS, "dealbreaker_tags");
  const standout = parseText(submission, standoutF.aliases, standoutF.column, purposeToQid);
  const memory = parseText(submission, memoryF.aliases, memoryF.column, purposeToQid);
  const lovedThisTime = parseTagList(submission, lovedF.aliases, lovedF.column, purposeToQid);
  const dealbreakersThisTime = parseTagList(submission, dealF.aliases, dealF.column, purposeToQid);

  const prefs = selectPreferencesForEmail(preferences);

  const blocks = [];
  blocks.push(
    '<p style="margin:0 0 16px 0;">Hi ' + escapeHtml(firstName) + ",</p>" +
    '<p style="margin:0 0 16px 0;">Thanks for sending your feedback on the home we toured on ' +
      escapeHtml(showingDate) + ". Here is a recap for your records.</p>"
  );

  blocks.push(
    '<h3 style="margin:24px 0 8px 0;color:#222;">Property</h3>' +
    '<p style="margin:0 0 4px 0;font-weight:600;">' + escapeHtml(propertyAddress) + "</p>" +
    (stats ? '<p style="margin:0;color:#555;">' + escapeHtml(stats) + "</p>" : "")
  );

  if (ratingRowsHtml.length > 0) {
    blocks.push(
      '<h3 style="margin:24px 0 8px 0;color:#222;">Your Ratings</h3>' +
      '<table style="border-collapse:collapse;">' + ratingRowsHtml.join("") + "</table>"
    );
  }

  if (lovedThisTime.length > 0) {
    blocks.push(
      '<h3 style="margin:24px 0 8px 0;color:#222;">What you loved about this one</h3>' +
      tagListHtml(lovedThisTime, "#2f855a")
    );
  }

  if (dealbreakersThisTime.length > 0) {
    blocks.push(
      '<h3 style="margin:24px 0 8px 0;color:#222;">Dealbreakers on this one</h3>' +
      tagListHtml(dealbreakersThisTime, "#c05621")
    );
  }

  if (standout) {
    blocks.push(
      '<h3 style="margin:24px 0 8px 0;color:#222;">What stood out</h3>' +
      '<p style="margin:0;">' + escapeHtml(standout).replace(/\n/g, "<br>") + "</p>"
    );
  }

  if (memory) {
    blocks.push(
      '<h3 style="margin:24px 0 8px 0;color:#222;">Other things to remember</h3>' +
      '<p style="margin:0;">' + escapeHtml(memory).replace(/\n/g, "<br>") + "</p>"
    );
  }

  if (prefs) {
    const prefHtml = buildPreferencesBlockHtml(prefs);
    blocks.push(prefHtml);
  }

  blocks.push(buildSignatureHtml(owner));

  return (
    '<!doctype html><html><body style="font-family:-apple-system,BlinkMacSystemFont,\'Segoe UI\',Arial,sans-serif;color:#222;line-height:1.5;max-width:600px;margin:0 auto;padding:24px;">' +
    blocks.join("") +
    "</body></html>"
  );
}

// Build the email signature block from owner env vars. Phone, email,
// and website lines render only when the corresponding var is set.
function buildSignatureHtml(owner) {
  const parts = [];
  parts.push('<p style="margin:24px 0 16px 0;color:#555;">If anything changed or you want to add to this, just reply to this email.</p>');
  parts.push('<p style="margin:0;font-weight:600;color:#222;">' + escapeHtml(owner.fullName) + '</p>');
  if (owner.brokerage) {
    parts.push('<p style="margin:0;color:#555;">' + escapeHtml(owner.brokerage) + '</p>');
  }
  if (owner.phone) {
    const phoneDigits = owner.phone.replace(/[^0-9+]/g, "");
    parts.push('<p style="margin:0;"><a href="tel:' + phoneDigits + '" style="color:#2c5282;text-decoration:none;">' + escapeHtml(owner.phone) + '</a></p>');
  }
  if (owner.email) {
    parts.push('<p style="margin:0;"><a href="mailto:' + escapeHtml(owner.email) + '" style="color:#2c5282;text-decoration:none;">' + escapeHtml(owner.email) + '</a></p>');
  }
  if (owner.website) {
    const display = owner.website.replace(/^https?:\/\//, "").replace(/^www\./, "").replace(/\/$/, "");
    const href = owner.website.startsWith("http") ? owner.website : "https://" + owner.website;
    parts.push('<p style="margin:2px 0 0 0;"><a href="' + escapeHtml(href) + '" style="color:#2c5282;text-decoration:none;">' + escapeHtml(display) + '</a></p>');
  }
  return parts.join("");
}

function tagListHtml(tags, color) {
  const chips = tags
    .map(
      (t) =>
        '<span style="display:inline-block;margin:2px 6px 2px 0;padding:4px 10px;background:' +
        color +
        '15;color:' +
        color +
        ';border:1px solid ' +
        color +
        '40;border-radius:999px;font-size:13px;">' +
        escapeHtml(t) +
        "</span>"
    )
    .join("");
  return '<div style="margin:0;">' + chips + "</div>";
}

function buildPreferencesBlockHtml(prefs) {
  const lovedRows = prefs.loved
    .map(
      (item) =>
        '<li style="margin:2px 0;">' +
        escapeHtml(item.tag) +
        ' <span style="color:#888;font-size:13px;">(' +
        item.count +
        " of " +
        prefs.total_showings +
        " showings)</span></li>"
    )
    .join("");
  const dealRows = prefs.dealbreakers
    .map(
      (item) =>
        '<li style="margin:2px 0;">' +
        escapeHtml(item.tag) +
        ' <span style="color:#888;font-size:13px;">(' +
        item.count +
        " of " +
        prefs.total_showings +
        " showings)</span></li>"
    )
    .join("");

  const parts = [];
  parts.push(
    '<div style="margin:32px 0 0 0;padding:16px 20px;background:#f7f5ef;border-left:4px solid #C89F50;border-radius:4px;">'
  );
  parts.push(
    '<h3 style="margin:0 0 4px 0;color:#222;">What we are learning about your preferences</h3>'
  );
  parts.push(
    '<p style="margin:0 0 12px 0;color:#666;font-size:13px;">Based on your feedback across ' +
      prefs.total_showings +
      " showings.</p>"
  );
  if (lovedRows) {
    parts.push(
      '<p style="margin:8px 0 4px 0;font-weight:600;color:#2f855a;">Things you keep coming back to</p>' +
      '<ul style="margin:0 0 8px 18px;padding:0;">' + lovedRows + "</ul>"
    );
  }
  if (dealRows) {
    parts.push(
      '<p style="margin:8px 0 4px 0;font-weight:600;color:#c05621;">Things to avoid</p>' +
      '<ul style="margin:0 0 0 18px;padding:0;">' + dealRows + "</ul>"
    );
  }
  parts.push("</div>");
  return parts.join("");
}

function escapeHtml(s) {
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}
